modLoader="javafml"
loaderVersion="[40,)"
license="license.txt"
issueTrackerURL="https://github.com/AgriCraft/AgriCraft/issues/"

[[mods]]
modId="agricraft"
version="1.18.2-3.1.3"
displayName="AgriCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/agricraft"
updateJSONURL = "https://raw.githubusercontent.com/AgriCraft/AgriCraft/master/version.json"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Agricultural farming extended
'''
itemIcon="agricraft:debugger"

[[dependencies.agricraft]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.agricraft]]
    modId="infinitylib"
    mandatory=true
    versionRange="[1.18.2-2.1.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.agricraft]]
    modId="betterweather"
    mandatory=false
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.agricraft]]
    modId="botanypots"
    mandatory=false
    versionRange="[1.16.5-7.1.20,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.agricraft]]
    modId="cyclic"
    mandatory=false
    versionRange="[1.16.5-1.2.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.agricraft]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.16.5-5.0.0-135,)"
    ordering="AFTER"
    side="BOTH"