modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/AgriCraft/AgriCraft/issues/"

[[mods]]
modId="agricraft"
version="${version}"
displayName="AgriCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/agricraft"
updateJSONURL = "https://raw.githubusercontent.com/AgriCraft/AgriCraft/master/version.json"
logoFile="logo.png"
authors="InfinityRaider, Ketheroth"
description='''
Agricultural farming extended
'''

[[accessTransformers]]
file="accesstransformer.cfg"

[[dependencies.agricraft]]
modId="neoforge"
type="required"
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.agricraft]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.agricraft]]
modId = "resourcefulconfig"
type="required"
versionRange = "[${resourcefulconfig_version},)"
ordering = "NONE"
side = "BOTH"
